### ISSUE TITLE
Change setting, bookmark and history icon.

### ISSUE THREAD

**Issue by NarzaryU** [victagne/essor_french_dictionary#1]
I've just downloaded from play store.  Its amazing. But I feel that you should change the above mentioned icons.

Also try to give sliding feature.

**Comment by victagne** [comment]
Hi @NehemiahNarzary, icons will be updated. What sliding feature do you mean?

**Comment by NarzaryU** [comment]
By sliding feature I mean to go from search to history, bookmark,  setting
by sliding. See aard2 on github.

**Comment by NarzaryU** [comment]
See the icons also on aard2 dictionary.

**Comment by victagne** [comment]
ok @NehemiahNarzary, could you verify if the icons are corrected on your side? I just pushed them.

**Comment by NarzaryU** [comment]
Yes it's done.
